services:
  server:
    build:
      context: .          
      dockerfile: Dockerfile
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2359:2359"
    privileged: true
    restart: always

  worker:
    build:
      context: .          
      dockerfile: Dockerfile
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    restart: always

volumes:
  data:
