x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    image: judge0/judge0:latest
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - coolify
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.judge0.rule=Host(`judge0.jestsee.com`) && PathPrefix(`/`)"
      - "traefik.http.routers.judge0.entryPoints=http"
      - "traefik.http.routers.judge0.entryPoints=https"
      - "traefik.http.routers.judge0.tls=true"
      - "traefik.http.routers.judge0.tls.certresolver=letsencrypt"
      - "traefik.http.services.judge0.loadbalancer.server.port=2358"

  worker:
    image: judge0/judge0:latest
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always
    networks:
      - coolify

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always
    networks:
      - coolify

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always
    networks:
      - coolify

networks:
 coolify:
  name: coolify
  external: true

volumes:
  data: